name: Deploy Laravel to DigitalOcean

on:
  push:
    branches:
      - main  # Or master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
              cd /var/www/mobile-backend
              git reset --hard origin/main
              git clean -fd
              git pull origin main
              php artisan route:cache
              php artisan view:clear
              php artisan config:clear
              php artisan cache:clear
              php artisan config:cache
              php artisan view:cache

